# Generated by Django 5.0.6 on 2024-06-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo do produto')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('preco', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Preço do produto')),
            ],
        ),
    ]
