# Generated by Django 5.0.6 on 2024-07-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_compra_campo_delete_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.CharField(default='sim ', max_length=100, verbose_name='Esta em promoção?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.PositiveIntegerField(verbose_name='Preço do produto'),
        ),
    ]
